<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Project;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
      $projects = [
            [
                'title' => 'Creusement d\'un puits à Douar Tinzouline',
                'description' => 'Ce projet vise à creuser un puits équipé d\'une pompe solaire pour fournir de l\'eau potable à plus de 150 familles isolées.',
                'goalAmount' => 45000,
                'currentAmount' => 12500,
                'startDate' => $now->copy()->subDays(10),
                'endDate' => $now->copy()->addDays(30),
                'status' => 'OPEN',
                'videoUrl' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'category_id' => 1,
                'association_id' => 1,
            ],
            [
                'title' => 'Canalisation d\'eau pour l\'école du village',
                'description' => 'Acheminement de l\'eau courante vers l\'école rurale locale pour améliorer l\'hygiène des élèves.',
                'goalAmount' => 20000,
                'currentAmount' => 20000,
                'startDate' => $now->copy()->subDays(40),
                'endDate' => $now->copy()->subDays(5),
                'status' => 'COMPLETED',
                'videoUrl' => null,
                'category_id' => 1,
                'association_id' => 1,
            ],

            [
                'title' => 'Éclairage Solaire pour 50 foyers',
                'description' => 'Installation de kits de panneaux solaires individuels pour les familles vivant hors réseau électrique dans le Haut Atlas.',
                'goalAmount' => 60000,
                'currentAmount' => 5000,
                'startDate' => $now->copy()->subDays(2),
                'endDate' => $now->copy()->addDays(60),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 1,
                'association_id' => 2,
            ],
            [
                'title' => 'Construction d\'un petit pont piétonnier',
                'description' => 'Construction d\'un pont sûr pour permettre aux enfants de traverser la rivière en hiver pour aller à l\'école.',
                'goalAmount' => 35000,
                'currentAmount' => 15000,
                'startDate' => $now->copy()->subDays(15),
                'endDate' => $now->copy()->addDays(45),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 1,
                'association_id' => 2,
            ],

            [
                'title' => 'Sacs à dos et fournitures pour la rentrée',
                'description' => 'Distribution de 500 cartables complets pour lutter contre la déperdition scolaire dans la région.',
                'goalAmount' => 25000,
                'currentAmount' => 25000,
                'startDate' => $now->copy()->subMonths(6),
                'endDate' => $now->copy()->subMonths(4),
                'status' => 'CLOSED',
                'videoUrl' => null,
                'category_id' => 2,
                'association_id' => 3,
            ],
            [
                'title' => 'Achat d\'un Minibus de Transport Scolaire',
                'description' => 'Acquisition d\'un minibus pour transporter les filles des villages avoisinants vers le collège rural.',
                'goalAmount' => 120000,
                'currentAmount' => 45000,
                'startDate' => $now->copy()->subDays(5),
                'endDate' => $now->copy()->addDays(80),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 2,
                'association_id' => 3,
            ],

            [
                'title' => 'Rénovation d\'une école à la périphérie',
                'description' => 'Peinture, réparation des fenêtres et aménagement d\'un espace de jeux pour une école publique.',
                'goalAmount' => 40000,
                'currentAmount' => 12000,
                'startDate' => $now->copy()->subDays(20),
                'endDate' => $now->copy()->addDays(20),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 2,
                'association_id' => 4,
            ],
            [
                'title' => 'Bibliothèque éducative pour tous',
                'description' => 'Aménagement d\'une salle de lecture avec achat de 1000 livres et contes pour enfants.',
                'goalAmount' => 15000,
                'currentAmount' => 8000,
                'startDate' => $now->copy()->subDays(10),
                'endDate' => $now->copy()->addDays(50),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 2,
                'association_id' => 4,
            ],

            [
                'title' => 'Caravane Médicale Ophtalmologique',
                'description' => 'Organisation d\'une caravane pour réaliser 100 opérations gratuites de la cataracte pour les personnes âgées.',
                'goalAmount' => 80000,
                'currentAmount' => 60000,
                'startDate' => $now->copy()->subDays(25),
                'endDate' => $now->copy()->addDays(15),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 3,
                'association_id' => 5,
            ],
            [
                'title' => 'Équipement d\'un dispensaire de quartier',
                'description' => 'Achat de matériel de premiers secours, tensiomètres et lecteur de glycémie.',
                'goalAmount' => 30000,
                'currentAmount' => 30000,
                'startDate' => $now->copy()->subMonths(2),
                'endDate' => $now->copy()->subMonths(1),
                'status' => 'COMPLETED',
                'videoUrl' => null,
                'category_id' => 3,
                'association_id' => 5,
            ],

            [
                'title' => 'Prise en charge d\'opérations cardiaques (Enfants)',
                'description' => 'Soutien financier pour sauver la vie de 3 enfants nécessitant des chirurgies cardiaques urgentes.',
                'goalAmount' => 150000,
                'currentAmount' => 45000,
                'startDate' => $now->copy()->subDays(5),
                'endDate' => $now->copy()->addDays(40),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 3,
                'association_id' => 6,
            ],
            [
                'title' => 'Achat de médicaments pour maladies chroniques',
                'description' => 'Fourniture mensuelle d\'insuline et traitements pour 50 patients démunis.',
                'goalAmount' => 20000,
                'currentAmount' => 15000,
                'startDate' => $now->copy()->subDays(10),
                'endDate' => $now->copy()->addDays(20),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 3,
                'association_id' => 6,
            ],

            [
                'title' => 'Parrainage de 20 Orphelins (Annuel)',
                'description' => 'Assurer les frais de scolarité, nourriture et vêtements pour 20 enfants ayant perdu leurs parents.',
                'goalAmount' => 60000,
                'currentAmount' => 10000,
                'startDate' => $now->copy()->subDays(2),
                'endDate' => $now->copy()->addDays(90),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 4,
                'association_id' => 7,
            ],
            [
                'title' => 'Projet "Kafalat Ar-Armala"',
                'description' => 'Aide au lancement de petits projets générateurs de revenus (couture, pâtisserie) pour 5 veuves.',
                'goalAmount' => 25000,
                'currentAmount' => 25000,
                'startDate' => $now->copy()->subMonths(3),
                'endDate' => $now->copy()->subMonths(2),
                'status' => 'CLOSED',
                'videoUrl' => null,
                'category_id' => 4,
                'association_id' => 7,
            ],

            [
                'title' => 'Couffins Alimentaires de Ramadan',
                'description' => 'Distribution de 1000 paniers alimentaires contenant les nécessités de base pour le mois sacré.',
                'goalAmount' => 100000,
                'currentAmount' => 85000,
                'startDate' => $now->copy()->subDays(15),
                'endDate' => $now->copy()->addDays(15),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 4,
                'association_id' => 8,
            ],
            [
                'title' => 'Abris et vêtements chauds pour l\'hiver',
                'description' => 'Campagne de maraude nocturne pour fournir repas chauds et manteaux aux sans-abris de la ville.',
                'goalAmount' => 30000,
                'currentAmount' => 12000,
                'startDate' => $now->copy()->subDays(8),
                'endDate' => $now->copy()->addDays(50),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 4,
                'association_id' => 8,
            ],

            [
                'title' => 'Tentes et logistique post-séisme',
                'description' => 'Fonds d\'urgence pour l\'achat et l\'installation de tentes robustes pour les sinistrés.',
                'goalAmount' => 200000,
                'currentAmount' => 195000,
                'startDate' => $now->copy()->subDays(5),
                'endDate' => $now->copy()->addDays(10),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 5,
                'association_id' => 9,
            ],
            [
                'title' => 'Campagne Grand Froid Atlas',
                'description' => 'Achat massif de couvertures épaisses et de bois de chauffage pour les villages encerclés par la neige.',
                'goalAmount' => 50000,
                'currentAmount' => 50000,
                'startDate' => $now->copy()->subMonths(5),
                'endDate' => $now->copy()->subMonths(4),
                'status' => 'COMPLETED',
                'videoUrl' => null,
                'category_id' => 5,
                'association_id' => 9,
            ],

            [
                'title' => 'Reconstruction d\'habitations endommagées',
                'description' => 'Achat de matériaux de construction pour aider 10 familles à rebâtir leurs maisons après les inondations.',
                'goalAmount' => 150000,
                'currentAmount' => 40000,
                'startDate' => $now->copy()->subDays(12),
                'endDate' => $now->copy()->addDays(48),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 5,
                'association_id' => 10,
            ],
            [
                'title' => 'Convoi alimentaire d\'urgence',
                'description' => 'Envoi de camions remplis de denrées non périssables vers les zones déclarées sinistrées.',
                'goalAmount' => 45000,
                'currentAmount' => 20000,
                'startDate' => $now->copy()->subDays(3),
                'endDate' => $now->copy()->addDays(27),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 5,
                'association_id' => 10,
            ],

            [
                'title' => 'Achat de 50 Chaises Roulantes',
                'description' => 'Offrir des chaises roulantes manuelles et électriques pour faciliter la mobilité des personnes en situation de handicap.',
                'goalAmount' => 75000,
                'currentAmount' => 32000,
                'startDate' => $now->copy()->subDays(18),
                'endDate' => $now->copy()->addDays(42),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 6,
                'association_id' => 11,
            ],
            [
                'title' => 'Aménagement d\'un centre de rééducation',
                'description' => 'Équiper une salle de kinésithérapie avec le matériel nécessaire pour des séances de rééducation gratuites.',
                'goalAmount' => 120000,
                'currentAmount' => 15000,
                'startDate' => $now->copy()->subDays(1),
                'endDate' => $now->copy()->addDays(60),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 6,
                'association_id' => 11,
            ],

            [
                'title' => 'Machines d\'écriture Braille pour Étudiants',
                'description' => 'Financement de 20 machines Perkins pour aider les étudiants malvoyants à poursuivre leurs études universitaires.',
                'goalAmount' => 80000,
                'currentAmount' => 80000,
                'startDate' => $now->copy()->subMonths(4),
                'endDate' => $now->copy()->subMonths(3),
                'status' => 'COMPLETED',
                'videoUrl' => null,
                'category_id' => 6,
                'association_id' => 12,
            ],
            [
                'title' => 'Achat de Cannes Blanches Électroniques',
                'description' => 'Fournir des cannes équipées de capteurs à ultrasons pour garantir la sécurité des déplacements en ville.',
                'goalAmount' => 40000,
                'currentAmount' => 18000,
                'startDate' => $now->copy()->subDays(7),
                'endDate' => $now->copy()->addDays(23),
                'status' => 'OPEN',
                'videoUrl' => null,
                'category_id' => 6,
                'association_id' => 12,
            ],
        ];

        foreach ($projects as $project) {
            DB::table('projects')->insert(array_merge($project, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

    }
}
